name: 'Push Workflow Data to Tinybird'
description: 'Pushes Github Workflow run attempt metadata to Tinybird'
author: 'localstack'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'upload-cloud'
  color: 'purple'

# Define your inputs here.
inputs:
  github_token:
    description: 'Github token for receiving start and end time of the workflow'
    required: true
  tinybird_token:
    description: 'The token to authenticate with Tinybird'
    required: true
  tinybird_datasource:
    description: 'The Tinybird datasource to which to push the data to'
    required: false
    default: 'ci_workflows'
  workflow_id:
    description: 'The id of the workflow'
  outcome:
    description: >
      Optional input to manually override the outcome reported to Tinybird.
      By default the outcome is calculated using the worst outcome of all jobs in the current workflow run attempt.
    required: false
  

runs:
  using: node20
  main: dist/index.js
